### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by huang47** [Reactive-Extensions/RxJS-CLI#3]
```shell
hhuang:/tmp/ $ rx -m select                                [20:53:01]
env: node\r: No such file or directory
```

`bin/rx` fileformat is `unix` but in npm package it's `dos`

**Comment by mattpodwysocki** [comment]
Closing issue thanks to @jfsiii

**Comment by Bartunek** [comment]
@jfsiii Thanks a lot! Now it works perfect with globaly installed RxJS-CLI.

**Comment by cpselvis** [comment]
Can you show commit link of your solution? I meet same problem when I write CLI in windows and try to let it works in OSX platform.

**Comment by jfsiii** [comment]
@cpselvis see cd977f4 linked above comment closing ticket
